export const CATALOG_SEARCH_VALUE= 'CATALOG_SEARCH_VALUE'
export const CATALOG_SEARCH_VALUE_DELETE= 'CATALOG_SEARCH_VALUE_DELETE'
export const CATALOG_SEARCH_VALUE_ISSEARCHING= 'CATALOG_SEARCH_VALUE_ISSEARCHING'
// export const CATALOG_SEARCH_HEADER= 'CATALOG_SEARCH_HEADER'