export const CATALOG_REQUEST = 'CATALOG_REQUEST'
export const CATALOG_ERROR = 'CATALOG_ERROR'
export const CATALOG_SUCCESS = 'CATALOG_SUCCESS'
export const CATALOG_FILTERED= 'CATALOG_FILTERED'
export const CATALOG_SUCCESS_MORE= 'CATALOG_SUCCESS_MORE'

